### ISSUE TITLE
Unable to read only specified columns from  the postgresql database

### ISSUE THREAD

**Issue by Swarnitha-eluru** [frictionlessdata/forum#54] opened 2020-06-16 12:26 UTC
I need to specify particular columns and read them(as like select statement) from the postgresql database .
I tried using pick_columns and skip_columns but it didnot worked it displayed only few columns out of specified ones.
this is the code written
![image](https://user-images.githubusercontent.com/46745717/84773764-836f0f80-affa-11ea-8b00-5e4b83b3c452.png)
This is the output I got it is not able to show all when I read its only showing in selected headers.
![image](https://user-images.githubusercontent.com/46745717/84773651-5a4e7f00-affa-11ea-833b-064ea1ab091a.png)

So please suggest on this

**Comment by rufuspollock** [comment] 2020-06-17 12:00
@Swarnitha-eluru can you give more details of what the db looks like and what your desired output is.

**Comment by Swarnitha-eluru** [comment] 2020-06-17 12:32
![image](https://user-images.githubusercontent.com/46745717/84898202-7fa7bf80-b0c4-11ea-8c5a-3c3c9a139649.png)

this is the data in my postgrsql 
i should read only  id,name,phnno columns from the table and write to .csv file or whatever it is.

**Comment by rufuspollock** [comment] 2020-06-17 20:28
So your bug is that it is writing all the columns?

**Comment by Swarnitha-eluru** [comment] 2020-06-18 03:43
yes i need to write only selected columns i.e among id,name,address,age,phnno of my table i want to read and write only id,name,phnno

**Comment by rufuspollock** [comment] 2020-06-18 05:31
@roll any thoughts?

**Comment by roll** [comment] 2020-06-18 12:57
Hi @Swarnitha-eluru,

The data discovery API (skip/pick/etc) is quite new and experimental. I was able to find a similar problem in it for keyed resources (like SQL) and now it's fixed with `tabulator@1.52.3`.

Please let me know if your problem still exists

**Comment by Swarnitha-eluru** [comment] 2020-06-18 13:09
ok thanks for the update

**Comment by Swarnitha-eluru** [comment] 2020-06-22 07:05
@roll I installed the version suggested by you.
I wrote code to skip some columns from the postgresql table.
![image](https://user-images.githubusercontent.com/46745717/85258113-8186cf80-b484-11ea-9d52-88ad5a44284a.png)
![image](https://user-images.githubusercontent.com/46745717/85258135-8f3c5500-b484-11ea-8ff9-2de649d1154d.png)

The issue I found was when I need 4 columns out of 5 as per my example,
its is showing the list of selected columns when I used stream.headers,but when i read them I am seeing only data of 3 columns for all the rows.
This is what i find in my testing.

**Comment by roll** [comment] 2020-06-22 12:50
@Swarnitha-eluru thanks for reporting! I'll investigate tomorrow

**Comment by Swarnitha-eluru** [comment] 2020-06-23 03:16
@roll thankyou

**Comment by roll** [comment] 2020-06-28 07:13
Hi @Swarnitha-eluru,

Sorry for the delay with the answer but I wasn't able to reproduce your problem. Could please share the table dump and the code you run as a text?

Also could you please ensure that 
```
print(tabulator.__version__)
# 1.52.3
```

**Comment by Swarnitha-eluru** [comment] 2020-06-29 03:20
hi @roll 
Its okay.I tested the version by including your print statement I got the version as 1.38.2 .I was really shocked as  I installed 1.52.3 few days back when you suggested .So I uninstalled the tabulator its showed me that i uninstalled 1.52.3.

After uninstalling I again installed 1.52.3 .Then I ran my code snippet It worked me well.
Thanks for solving and helping in this issue.

**Closed as completed** 2020-06-29 03:20 UTC
